name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  

    - name: Update npm to latest version
      run: npm install -g npm@latest

    - name: Install dependencies
      run: npm install

    - name: Update Browserslist database
      run: npx browserslist@latest --update-db

    - name: Build project
      env:
        CI: false  
      run: npm run build

    - name: Configure Git identity
      run: |
        git config --global user.email "mcmendezmanotas@gmail.com"
        git config --global user.name "mcmendez"

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run deploy
